---
# tasks file for tomcat_ssl
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define tomcat_packages.
  set_fact:
    tomcat_packages: "{{ __tomcat_packages | list }}"
  when: tomcat_packages is not defined

- include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Configure Tomcat.
  include_tasks: "configure-{{ ansible_os_family }}.yml"